# Generated by Django 5.0.2 on 2024-11-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_remove_category_created_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
